import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  containerz: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingTop: 0,
    marginTop: 0,
  },
  containeru: {
    flex: 1,
    height: 1000,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingTop: 0,
  },
  containers: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f2f2f2',
    paddingBottom: 0,
  },
  containersS: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingBottom: 25,
    marginTop: 45,
    marginHorizontal: 10
  },
  text: {
    color: 'azure',
    paddingHorizontal: 97,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 8,
    borderWidth: 0.75,
    fontSize: 18,
    width: 240,
    backgroundColor: '#ff99cc',
    borderColor: '#6666ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textz: {
    color: 'azure',
    paddingHorizontal: 70,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 8,
    borderWidth: 0.75,
    fontSize: 18,
    width: 240,
    backgroundColor: '#ff99cc',
    borderColor: '#6666ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  textinput: {
    width: 250,
    marginBottom: 15,
    height: 40,
    fontSize: 18,
  },
  textinputV: {
    width: 200,
    height: 200,
    fontSize: 20,
    backgroundColor: "#ffffff"
  },
  header: {
    fontSize: 20,
    backgroundColor: '#4173CE'
  },
  highlighted: {
    color: 'blue',
    fontSize: 16,
  },
  cardP: {
    borderRadius: 15,
    borderWidth: 2,
    marginVertical: 10,
    borderColor: "#ff99cc",
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "#fff",
    flex: 1.01,
    width: 290,
    height: 40
  },
  card: {
    borderRadius: 15,
    borderWidth: 2,
    marginVertical: 10,
    borderColor: "#6666ff",
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "#fff",
    flex: 1.01,
    width: 290,
    height: 40
  },
  addButton: {
    flex: 1,
    borderRadius: 15,
    paddingHorizontal: 125,
    paddingTop: 10,
    paddingBottom: 10,
    borderWidth: 0.4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "#4173CE",
    borderColor: "#4173CE",
    height: 40,

  },
  addButtonB: {
    borderRadius: 15,
    paddingHorizontal: 30,
    paddingTop: 10,
    paddingBottom: 10,
    borderWidth: 0.5,
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "#4173CE",
    borderColor: "#4173CE",
    height: 40,

  },
  no: {
    flex: 0.5,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 90,
    marginHorizontal: 60,
    marginVertical: 5,
    height: 35,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "red",
  },
  yes: {
    flex: 0.5,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 50,
    marginHorizontal: 60,
    marginVertical: 5,
    height: 35,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "green",
  },
  welcomez: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 25,
    paddingHorizontal: 10,
    alignItems: 'center',
    backgroundColor: '#f2f2f2',
  },
  welcomezz: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 25,
    paddingHorizontal: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  textR: {
    color: 'azure',
    paddingHorizontal: 72,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 8,
    borderWidth: 0.75,
    fontSize: 18,
    width: 240,
    backgroundColor: '#ff99cc',
    borderColor: '#6666ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  list: {
    flex: 1,
    paddingTop: 54,
    paddingLeft: 16,
  },
  row: {
    flex: 1,
    padding: 8,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
    borderBottomWidth: 1,
  },
  rowTitle: {
    fontSize: 14,
  },
  rowDescription: {
    fontSize: 12,
  },
});

